### ISSUE TITLE
Page not Opening!

### ISSUE THREAD

**Issue by mehmetakifkucuk** [prestondunton/marvel-dialogue-nlp#5]
Hi,
Getting the following error while trying to open the following link.
Thanks,
Akif,

_**Link**_
https://share.streamlit.io/prestondunton/marvel-dialogue-nlp/front_end/front-end.py

**_Error:_**
Oh no.
Error running app. If this keeps happening, please file an issue.

**Comment by prestondunton** [comment]
Thanks for bringing this to my attention.  It just looks like some libraries and saved data objects are on different versions.  I'll take a look at it when I get a second and fix the issue.

**Comment by prestondunton** [comment]
Should be resolved.  Sklearn updated to version 0.24.1 and my pickled objects had version 0.23.1.  I just changed the requirements to have version 0.23.1 instead of rebuilding my pickled objects (training takes a while and I'm lazy).  Let me know if there's still an issue.  Thanks agian.

**Comment by mehmetakifkucuk** [comment]
Thanks, working now!
